---
  summary_host:
    description: "Please fill in"
    type: "string"
    required: false

  summary_user:
    description: "Please fill in"
    type: "string"
    required: false

  summary_host_key:
    description: "Please fill in"
    type: "string"
    required: false

  summary_destination:
    description: "Please fill in"
    type: "string"
    required: false


  remote_host:
    description: "Please fill in"
    type: "string"
    required: false

  remote_user:
    description: "Please fill in"
    type: "string"
    required: false

  remote_host_key:
    description: "Please fill in"
    type: "string"
    required: false

  remote_destination:
    description: "Please fill in"
    type: "string"
    required: false

  send_mail_to:
    description: "Please fill in"
    type: "string"
    required: false

  runfolder_service_port:
    description: "Please fill in"
    type: "integer"
    required: false

  bcl2fastq_service_port:
    description: "Please fill in"
    type: "integer"
    required: false

  slack_webhook_url:
    description: "Please fill in"
    type: "string"
    required: false
